### ISSUE TITLE
bootstrap should pass **kwargs to f

### ISSUE THREAD

**Issue by erblast** [dsaxton/resample#2]
Hi,
I really like your package, I prefer it to the [bootstrapped package](https://github.com/facebookincubator/bootstrapped) because I am more flexible in customizing my summary statistics function that I pass to bootstrap(). However it would be great if I could also pass some **kwargs along with it. I would be happy to send you a pull request on that. 

I use your package to calculate [prediction intervalls](https://github.com/erblast/predictionintervalls)

**Comment by dsaxton** [comment]
Thanks for your interest!  Can I ask what application you have in mind?  Note that the function `f` can already return essentially anything, including an array of function values (in this notebook I use it to return a dictionary of summary statistics: https://github.com/dsaxton/resample/blob/master/examples/resample.ipynb), so it might already suit your needs. (Also, not sure if it was intentional but "interval" has one "l" rather than two.)

**Comment by dsaxton** [comment]
You should be able to address this by using a lambda function: `f=lambda x: get_stats(x, original_sample, intervals)` (if you want to avoid having global variables you could define the values of the arguments inside the call to `get_stats` itself).  I think this makes intuitive sense as `original_sample` and `intervals` are really arguments of `f` rather than `bootstrap`.
