### ISSUE TITLE
bootstrap(sample, fcn) or bootstrap(fcn, sample) ?

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#29]
@dsaxton I think we discussed this already somewhere, but which one do you prefer

`bootstrap(sample, fcn)` or `bootstrap(fcn, sample)`?

Somehow, intuitively, I would go for the latter, but I cannot rationalize it. In the original design, `fcn` had to be the second argument, because it was optional. In the new design, we have the generators to generate the samples, so the `fcn` argument in `bootstrap` is now mandatory.

**Comment by dsaxton** [comment]
@HDembinski Yes, I agree that the latter feels more natural, since it's really the function / parameter that are the focus when doing bootstrapping. Splitting hairs a bit here, but how about `fn` over `fcn`? Slightly less to type, is more pronounceable in abbreviated form, and also happens to match syntax used in other languages like Clojure and Rust.

**Comment by HDembinski** [comment]
Ok, fn instead of fcn.
