### ISSUE TITLE
Add `bootstrap_bias`

### ISSUE THREAD

**Issue by HDembinski** [dsaxton/resample#6]
There is `jackknife_bias`, so it would be nice to also have `bootstrap_bias`.

**Comment by dsaxton** [comment]
Sounds like a good idea to me 👍

**Comment by HDembinski** [comment]
Feel free to assign to me, with contributor rights I cannot assign to myself...

**Comment by HDembinski** [comment]
I spend more time thinking about this, and now I am not sure whether I can even compute the bias from the bootstrap? To estimate statistical bias, one (ideally) has to compute the statistic from subsamples of different size. The jackknife does this by computing all sub-samples with N-1 observations from the original sample, for example. The normal bootstrap, however, gives you a sample of the same size.

**Comment by dsaxton** [comment]
I think we can, we only need to compare an average of bootstrapped statistics with the original statistic (thinking of the former as an estimate of the expected value and the original as the "true" parameter value, so that the difference is a measure of bias).

https://stats.stackexchange.com/questions/129478/when-is-the-bootstrap-estimate-of-bias-valid

**Comment by HDembinski** [comment]
Thank you for the link, I used to have Efron's book about the bootstrap at hand, but I don't have it anymore to look this up. It was my impression that this simple formula is correct, but then I started to doubt it. The SO answer reaffirmed this, though.

**Comment by HDembinski** [comment]
I will also add that to #28

**Comment by HDembinski** [comment]
Sorry, changed my mind, I will do that in a separate PR.

**Comment by HDembinski** [comment]
Addressed in #40
